### ISSUE TITLE
"Arguments to pooler must be lists"

### ISSUE THREAD

**Issue by umyta** [facebookresearch/meshrcnn#12]
Hi, thanks for sharing your code. I am following pix3d training steps, and I run into this error:
```
Traceback (most recent call last):
  File ".../detectron2/detectron2/engine/train_loop.py", line 132, in train
  File ".../detectron2/detectron2/engine/train_loop.py", line 212, in run_step
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File ".../detectron2/detectron2/modeling/meta_arch/rcnn.py", line 129, in forward
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File ".../meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 150, in forward
  File ".../detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 619, in _forward_box
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
  File ".../detectron2/detectron2/modeling/poolers.py", line 199, in forward
AssertionError: Arguments to pooler must be lists
```

I looked into it and found that the features that are passed in at line 150 of `roi_heads.py` is a dictionary that contains keys ['p2', 'p3', 'p4', 'p5', 'p6']. Which one is used for the paper? Any help would be much appreciated. Thanks.

**Comment by gkioxari** [comment]
There was a [commit](https://github.com/facebookresearch/meshrcnn/commit/948bdcef6624ea3ac5cc1595e834416d95aec37f) a couple days ago that changed a few things on detectron2 and meshrcnn. Can you verify you have both these updates for both codebases?

**Comment by umyta** [comment]
Thanks for your quick response. I just updated both, and now the error becomes:

```
[02/21 22:17:06 d2.data.common]: Serializing 7537 elements to byte tensors and concatenating them all ...
Traceback (most recent call last):
  File "tools/train_net.py", line 111, in <module>
    args=(args,),
  File "/ec/pdx/disks/aipg_lab_home_pool_02/liusaina/workspace/panoptic3d/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/nfs/pdx/home/liusaina/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/nfs/pdx/home/liusaina/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGKILL
```

Do you have any suggestions?

**Comment by gkioxari** [comment]
Can you provide some specs for the machine you are using. Number of gpus, gpu types, cpu specs, memory specs etc.? This looks like an issue with your resources running out of memory.

**Comment by ppwwyyxx** [comment]
@umyta  A recent change in detectron2 leads to a significantly larger memory footprint for the type of data meshrcnn uses. For now you can workaround this by setting `serialize` to False at https://github.com/facebookresearch/detectron2/blob/c14fcaee32b253e9b76b78a56053f159e5e5ada0/detectron2/data/common.py#L65. We'll work on addressing this issue.

**Comment by gkioxari** [comment]
Yes! @ppwwyyxx has some amazing investigative skills! But we will try to fix this as soon as possible!

**Comment by umyta** [comment]
Thank you for all the suggestions. I'll give it a try later today.

**Comment by shihfangchen** [comment]
Hi there is a similar issue when it runs Mesh R-CNN on my own input image

![image](https://user-images.githubusercontent.com/14999043/75223869-534cf800-57e2-11ea-8fd5-b1a3227ead22.jpg)

both of my detectron2 and meshrcnn are up-to-date.

and meshrcnn_R50.pth are in the correct path

when I implement the INSTRUCTION of INSTRUCTIONS_PIX3D.md 
it also has the issue of "Arguments to pooler must be lists"

what would you suggest to solve that?

**Comment by ppwwyyxx** [comment]
@shihfangchen your detectron2 is not up-to-date because line622 of `roi_heads.py` in your image is different from https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/roi_heads.py#L622

**Comment by shihfangchen** [comment]
@ppwwyyxx Thanks I will try it.

**Comment by umyta** [comment]
It works for me too. I'm closing this issue. Thank you for all your help!

**Comment by gkioxari** [comment]
I am working on fixing this however so that you don't have to change this in D2. It will allow you to install D2 from a prebuilt package and run it! But glad this works too :)

**Comment by umyta** [comment]
Hi @gkioxari , the code was running fine during training, but during testing, a new error showed up:


```
...
[02/25 15:14:46 fvcore.common.checkpoint]: Saving checkpoint to ./output/model_final.pth
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[02/25 15:14:50 meshrcnn.data.datasets.pix3d]: Loaded 2530 images in COCO format from datasets/pix3d/pix3d_s1_test.json
[02/25 15:14:50 meshrcnn.data.datasets.pix3d]: Unique objects 735
[02/25 15:22:40 meshrcnn.data.datasets.pix3d]: Done loading models
[02/25 15:22:40 d2.data.build]: Distribution of instances among all 9 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|    bed     | 213          |  bookcase  | 79           |   chair    | 1165         |
|    desk    | 154          |    misc    | 20           |    sofa    | 415          |
|   table    | 419          |    tool    | 11           |  wardrobe  | 54           |
|            |              |            |              |            |              |
|   total    | 2530         |            |              |            |              |
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!                                                                                                [46/1961]
[02/25 15:22:41 d2.evaluation.evaluator]: Start inference on 633 images
Done (t=0.13s)
creating index...
index created!
Done (t=0.13s)
creating index...
index created!
loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train_net.py", line 111, in <module>
    args=(args,),
  File ".../detectron2/detectron2/engine/launch.py", line
 49, in launch
    daemon=False,
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", li
ne 171, in spawn
    while not spawn_context.join():
  File "..../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", li
ne 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", li
ne 19, in _wrap
  File ".../detectron2/detectron2/engine/launch.py", line
 84, in _distributed_worker
  File ".../meshrcnn/tools/train_net.py", line 99, in mai
n
    return trainer.train()
  File ".../detectron2/detectron2/engine/defaults.py", li
ne 380, in train
  File ".../detectron2/detectron2/engine/train_lo[9/1961]
line 133, in train
  File ".../detectron2/detectron2/engine/train_loop.py", 
line 154, in after_step
  File ".../detectron2/detectron2/engine/hooks.py", line 
350, in after_step
  File ".../detectron2/detectron2/engine/hooks.py", line 
324, in _do_eval
  File ".../detectron2/detectron2/engine/defaults.py", li
ne 331, in test_and_save_results
  File ".../meshrcnn/tools/train_net.py", line 63, in tes
t
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File ".../detectron2/detectron2/evaluation/evaluator.py
", line 117, in inference_on_dataset
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", li
ne 279, in __iter__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", li
ne 719, in __init__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/process.py", line 105, in start
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, i
n __init__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __ini
t__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, i
n _launch
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/reductions.py
", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_99012_1802213686> in read-write mode

 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_mai
n
 exitcode = _main(fd)
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
.../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: se
maphore_tracker: There appear to be 31 leaked semaphores to clean up at shutdown
  len(cache))
```

I updated pytorch3d, meshrcnn and detectron2 and pip installed all 3 again. Then run with eval-only mode, I got a different memory error:

```
Traceback (most recent call last):
  File "tools/train_net.py", line 111, in <module>
    args=(args,),
  File ".../detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
  File ".../detectron2/detectron2/engine/launch.py", line 84, in _distributed_worker
  File ".../meshrcnn/tools/train_net.py", line 94, in main
    res = Trainer.test(cfg, model)
  File ".../meshrcnn/tools/train_net.py", line 63, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File ".../detectron2/detectron2/evaluation/evaluator.py", line 117, in inference_on_dataset
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/process.py", line 105, in start
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
  File ".../anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_105736_469621813> in read-write mode
```
The script I run is "python tools/train_net.py --num-gpus 4 --config-file configs/pix3d/meshrcnn_R50_FPN.yaml --eval-only". It looks like an out of memory error, so I reduced the image batch size by adding SOLVER.IMS_PER_BATCH 2, I'm not sure if that's the correct way to do it here, but the error is still there. However, running demo code does not trigger this error. I was able to run demo code with the trained model.

**Comment by gkioxari** [comment]
Hi @umyta! I will update the codebase soon to handle the data serialization change in d2. It should be in by tomorrow the latest. I think this is related to the serialization change in d2. I am currently not getting this error when I run it (with the new change that will be coming tomorrow!)

**Comment by umyta** [comment]
@gkioxari Awesome, thanks for the update. Looking forward to the changes!

**Comment by gkioxari** [comment]
@umyta the fix is pushed! Give it a go!

**Comment by karthik1290** [comment]
Even with the latest commit of meshRCNN i still get this error
```
[02/28 12:05:58 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='input.jpg', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://meshrcnn_R50.pth'], output='output_demo')
Traceback (most recent call last):
  File "demo/demo.py", line 227, in <module>
    predictions = demo.run_on_image(img, focal_length=args.focal_length)
  File "demo/demo.py", line 59, in run_on_image
    predictions = self.predictor(image)
  File "myvenv/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 196, in __call__
    predictions = self.model([inputs])[0]
  File "myvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "myvenv/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 107, in forward
    return self.inference(batched_inputs)
  File "myvenv/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 169, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "myvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 162, in forward
    pred_instances = self._forward_box(features, proposals)
  File "myvenv/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 622, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "myvenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "myvenv/lib/python3.6/site-packages/detectron2/modeling/poolers.py", line 199, in forward
    ), "Arguments to pooler must be lists"
AssertionError: Arguments to pooler must be lists
```
Please let me know whether i should upgrade detectron2 ?

**Comment by gkioxari** [comment]
Please upgrade d2. Your issue is because you have an outdated d2 version. The fix I pushed was for a different issue, namely data serialization.

**Comment by karthik1290** [comment]
Ok thanks a lot.

**Comment by umyta** [comment]
@gkioxari Thank you for the update. I just finished testing the pipeline, both training and testing work now. I'm closing this issue.
